### PR TITLE
Remove preview checkbox

### PR DESCRIPTION
**Pull request by happycollision**
@aarkhipov40 switch to the `remove-preview-checkbox` branch and then run `npm run aws` to test and see if you like the way it works on the live site. Please review/comment below, but do not merge this PR.

### CODE REVIEW

**Comment by aarkhipov40** [comment]
I think you need to ignore the isPreview switch on data load back now.   The first time around all is good.  Once you edit a preview... I think the preview switch is on in the data, so even if you  click submit an order, it thinks that you are doing a preview and submits as preview.

**Comment by happycollision** [comment]
Oh right.

**Comment by happycollision** [comment]
I fixed and ran `aws` so you can test. Though I already did and it appears to be working.

**Comment by happycollision** [comment]
@aarkhipov40 Want me to go ahead and merge this? Does it work for you?

**Comment by aarkhipov40** [comment]
Yes, go ahead and merge.   It works great now.

**Pull request merged**
